### PR TITLE
#181339500-notification-panel

### PR DESCRIPTION
**Pull request by Code-250**
### What does this PR do?
 This PR implements notifications so that as a requester, manager, and travel admin on his/her notification panel
 
 ### description of the task
 - implements read notifications
 - increment notifications number icon
 - toast whenever there is a new notification
 ### How should this be tested manually?
- `git checkout feature/#181339500-notifications-panel` to go to this branch
- `yarn dev` to run the project
- log in as manager 
- on the other window log in as a requester: 
- click on notification icon to be able to see your notifications

### pivotal tracker task link
 [mark one/all notifications as read](https://www.pivotaltracker.com/story/show/181339512)
[Notification for requests update](https://www.pivotaltracker.com/story/show/181339500)

### Production link
[https://deploy-preview-21--barefoot-nomad-fe.netlify.app/](https://deploy-preview-21--barefoot-nomad-fe.netlify.app/)

### screenshot
Screen Shot 2022-06-03 at 12 22 43
- mobile view
Screen Shot 2022-06-06 at 10 27 13

### CODE REVIEW

**Review by Tsa2341 — CHANGES_REQUESTED** [review]
You did not add a way to test it, with the description on how to.
Also an image would be better added.

**Review by Gabin-ishimwe — APPROVED** [review]

**Comment by Code-250** [comment]
> You did not add a way to test it, with the description on how to. Also an image would be better added.

I have createeverything that is needed to be able to test my task.

**Review by ncutixavier — APPROVED** [review]

**Comment by ncutixavier** [comment]
image
Remove this part

**Comment by ncutixavier** [comment]
Also, check Logout because It's not working

**Comment by ncutixavier** [comment]
image
This type doesn't make sense compared with the notification message, I think you can remove it.

**Comment by Code-250** [comment]
> The notification model is not responsive on mobile image

I have made it responsive

**Comment by Code-250** [comment]
> image This type doesn't make sense compared with the notification message, I think you can remove it.

Thanks I have fixed it by removing the type on each notification.

**Comment by Code-250** [comment]
> image Remove this part

I have removed the notifications on our sidebar.

**Comment by ncutixavier** [comment]
- Logout is not working
- Remove all logs

**Comment by Code-250** [comment]
> * Logout is not working
> * Remove all logs

resolve tha issue of logout 
and removed the logs

**Review by ncutixavier — APPROVED** [review]

**Pull request merged**
